### ISSUE TITLE
Reduce Route Registrar logging

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/route-registrar#19]
route registrar is the 2nd highest logging component in my system.  I'd like to either be able to configure the log level of route registrar or perhaps make some of the info messages debug messages.

Thoughts?  If open to a PR I could put one together.

**Comment by shalako** [comment]
That sounds reasonable, we'd welcome a PR.

If you're proposing changing the log level of any message, please propose those changes first prior to submitting a PR.

**Comment by youngm** [comment]
@shalako So, I did a little digging and the problem log messages are the following with my proposed change:

https://github.com/cloudfoundry/route-registrar/blob/b133199d0f8e87f3e34e925832a44a6a4dc00c2d/registrar/registrar.go#L163
I'd propose this should be debug. I don't think it is useful information to know everytime the route registrar is about to do it's only job.

https://github.com/cloudfoundry/route-registrar/blob/b133199d0f8e87f3e34e925832a44a6a4dc00c2d/registrar/registrar.go#L170
I'd propose should be debug.  I don't think it is useful information to know everytime the route registrar successfully performs it's only job.

https://github.com/cloudfoundry/route-registrar/blob/b133199d0f8e87f3e34e925832a44a6a4dc00c2d/registrar/registrar.go#L84
I'd propose this should be debug as well, with a new message added at app startup time informing the user of the information.  Not every time the route registrar publishes routes.

Thoughts?

**Comment by shubhaat** [comment]
It's been a while @youngm but your proposal seems reasonable. We'll keep this open for now.

**Comment by youngm** [comment]
Thanks for reviewing this @shubhaat but I've found another way to trim route registrar's logging.  I'll reopen if I decide to work on this again.

**Comment by shubhaat** [comment]
Thanks for closing @youngm . Please feel free to reopen later if needed.
