### ISSUE TITLE
supporting yml for registrar_settings.yml.erb

### ISSUE THREAD

**Issue by gmflau** [cloudfoundry/route-registrar#22]
We are trying to upgrade our route-registrar to the latest version.  The old implementation was using a yml for registrar_settings config.  Do we have to switch to json format (registrar_settings.json.erb) in the latest route-registrar's implementation?

**Comment by rosenhouse** [comment]
Yes, it appears that this happened in https://github.com/cloudfoundry/route-registrar/commit/44f5123e91203d840b66ea200c0a0b20e88db3c3 as a result of https://github.com/cloudfoundry/routing-release/issues/86.  YAML will not work anymore.

I'm not sure we were considering that the settings file was an external-facing contract.  How severely does this impact you?

**Comment by shubhaat** [comment]
@gmflau operators use the bosh manifest to configure the route-registrar behavior. The supported spec is https://github.com/cloudfoundry/routing-release/blob/develop/jobs/route_registrar/spec. Changes in the file should be transparent to operators. This internal config file is not meant to be user facing. 

Closing this for now, please reopen if we are missing something here.
