### ISSUE TITLE
Multi port support for route-registrar

### ISSUE THREAD

**Issue by svennela** [cloudfoundry/route-registrar#24]
Created consul server as bosh release and exposed it as a route. But Consul server needs to expose multiple ports for the given route. If we can add ports variable to the release, below link as a reference for multi-port support in cf apps. https://gist.github.com/nota-ja/ef56ea0584ae2b37d6d3a535efe2d4ee. 

 route_registrar:
        routes:
        - name: consul
          ports: 7777,8888,8080
          registration_interval: 20s
          uris:
          - consul-bosh.(( ..cf.cloud_controller.system_domain.value ))

**Comment by shubhaat** [comment]
Hi @svennela , Would you be willing to make a PR for this? We are currently focussed on implementing an Istio and Envoy based routing system and might not be able to prioritize this, but we will accept a PR and prioritize reviewing and merging PRs.

**Comment by svennela** [comment]
Sure. Let you know.
